context:
  name: vir-simd
  version: "0.4.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mattkretz/vir-simd/archive/v${{ version }}.tar.gz
  sha256: 0d2953e1219798967b156aa392de6430099d85887770e5c81aefe8fb63e9464c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: ninja

tests:
  - package_contents:
      include:
        - vir/simd.h
      files:
        - ${{ "Library/" if win else "" }}lib/cmake/vir-simd/vir-simd-config.cmake

about:
  homepage: https://mattkretz.github.io/vir-simd/master/
  summary: 'A fallback std::experimental::simd (Parallelism TS 2) implementation with additional features.'
  description: |
    This project aims to provide a fallback std::experimental::simd
    (Parallelism TS 2) implementation with additional features. Not
    every user can rely on GCC 11+ and its standard library to be
    present on all target systems. Therefore, the header vir/simd.h
    provides a fallback implementation of the TS specification that
    only implements the scalar and fixed_size<N> ABI tags. Thus,
    your code can still compile and run correctly, even if it is
    missing the performance gains a proper implementation provides.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  documentation: https://github.com/mattkretz/vir-simd?tab=readme-ov-file#table-of-contents
  repository: https://github.com/mattkretz/vir-simd

extra:
  recipe-maintainers:
    - ax3l
    - mattkretz
